apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-demo-canary
  labels:
    app: rollouts-demo
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollouts-demo
      version: canary
  template:
    metadata:
      labels:
        app: rollouts-demo
        version: canary
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:green
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 100Mi